# Generated by Django 4.2.16 on 2025-05-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta1', models.CharField(max_length=100)),
                ('respuesta2', models.CharField(max_length=100)),
                ('respuesta3', models.CharField(max_length=100)),
                ('respuesta4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('nombre_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('Esta_de_examenes', models.BooleanField(null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=25, null=True)),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
            ],
            options={
                'unique_together': {('nombre_usuario', 'pregunta')},
            },
        ),
    ]
