# Generated by Django 4.2.16 on 2025-05-23 11:56

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('nombre_usuario', models.CharField(max_length=255, null=True, blank=True)),
                ('puntuacion', models.DecimalField(max_digits=5, decimal_places=3, null=True, blank=True)),
                ('Esta_de_examenes', models.BooleanField(null=True)),
                ('edad', models.IntegerField(null=True, blank=True)),
                ('sexo', models.CharField(
                    max_length=25,
                    choices=[
                        ('Hombre', 'Hombre'),
                        ('Mujer', 'Mujer'),
                        ('Prefiero no decirlo', 'Prefiero no decirlo')
                    ],
                    null=True, blank=True
                )),
                ('pregunta', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.Pregunta'
                )),
            ],
            options={
                'unique_together': {('nombre_usuario', 'pregunta')},
            },
        ),
    ]
