# Generated by Django 4.2.16 on 2025-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250523_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('util', models.BooleanField(null=True)),
                ('entendible', models.BooleanField(null=True)),
                ('repetiria', models.BooleanField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
