# Generated by Django 4.2.16 on 2025-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedbackfinal_alter_respuesta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackfinal',
            old_name='entendible',
            new_name='De_acuerdo_final',
        ),
        migrations.RenameField(
            model_name='feedbackfinal',
            old_name='repetiria',
            new_name='De_acuerdo_puntuaciones',
        ),
        migrations.RenameField(
            model_name='feedbackfinal',
            old_name='util',
            new_name='Ha_resultado_util',
        ),
        migrations.AddField(
            model_name='feedbackfinal',
            name='Lo_recomienda',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='feedbackfinal',
            name='Se_ha_entendido',
            field=models.BooleanField(null=True),
        ),
    ]
